In [2]:
import tensorflow
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display
from sklearn.model_selection import train_test_split

2026-03-03 21:06:21.717497: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-03 21:06:21.750309: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-03 21:06:22.633384: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

## Carga de datos

El primer paso es cargar los datos a utilizar.

In [4]:
DATA_DIR = "data/"
X_DATA = "FootballPlayerPreparedCleanAttributes.csv"
Y_DATA = "FootballPlayerOneHotEncodedClasses.csv"
x = pd.read_csv(DATA_DIR + X_DATA)
y = pd.read_csv(DATA_DIR + Y_DATA)

display(x.head())
display(y.head())

   Crossing  Finishing  HeadingAccuracy  ...  Penalties  Composure   Marking
0  0.170732   0.341176        -0.544304  ...      0.400   0.270270  0.023810
1 -0.243902   0.529412         0.493671  ...      0.700   0.270270 -0.380952
2  0.195122   0.717647         0.341772  ...      0.325   0.405405 -0.523810
3 -0.341463  -0.482353        -0.088608  ...     -0.300  -0.297297 -0.261905
4 -0.243902  -0.105882         0.443038  ...      0.175   0.189189  0.452381

[5 rows x 22 columns]

   Poor:[np.float64(46.0), np.float64(62.0)]  ...  Excel:[np.float64(72.0), np.float64(94.0)]
0                                        0.0  ...                                         0.0
1                                        0.0  ...                                         0.0
2                                        0.0  ...                                         1.0
3                                        1.0  ...                                         0.0
4                                        0.0  ...                                         0.0

[5 rows x 4 columns]

Y ahora separamos en train, test y validation.

In [5]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=42)
val_x, test_x, val_y, test_y = train_test_split(test_x, test_y, test_size=0.5, random_state=42)

print("Train set size:", len(train_x))
print("Validation set size:", len(val_x))
print("Test set size:", len(test_x))

Train set size: 12907
Validation set size: 1613
Test set size: 1614