In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


print(tf.config.list_physical_devices())

2026-03-09 17:38:59.143154: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-09 17:38:59.534794: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-09 17:39:02.996924: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
df_clean = pd.read_csv("FootballPlayerPreparedCleanAttributes.csv")
df_one_hot = pd.read_csv("FootballPlayerOneHotEncodedClasses.csv")
display(df_clean)
display(df_one_hot)

,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,...,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking
0,-0.707317,-0.811765,0.037975,-0.369863,-0.450,-0.445783,-0.662651,-0.500000,-0.729730,-0.518072,...,-0.014493,0.111111,-0.614458,0.219512,0.268293,-0.547619,-0.463415,-0.300,-0.027027,0.285714
1,0.365854,0.129412,0.063291,0.123288,0.250,0.590361,0.421687,0.166667,-0.324324,0.469880,...,0.188406,0.222222,0.349398,0.048780,-0.024390,0.333333,0.195122,0.500,0.351351,0.119048
2,0.341463,0.176471,-0.063291,0.178082,0.225,0.253012,0.469880,0.357143,-0.081081,0.228916,...,0.246377,0.166667,0.301205,0.487805,-0.439024,0.214286,0.219512,0.325,0.189189,-0.404762
3,-0.268293,-0.317647,-0.037975,0.287671,-0.300,0.132530,-0.373494,-0.238095,0.189189,0.204819,...,0.043478,-0.083333,0.421687,0.439024,0.317073,-0.380952,0.097561,-0.175,0.054054,0.428571
4,0.268293,-0.364706,0.139241,0.260274,0.100,0.084337,0.180723,0.238095,0.270270,0.180723,...,0.246377,0.333333,0.132530,0.268293,0.317073,-0.142857,0.243902,-0.175,0.162162,0.047619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16129,0.341463,0.388235,0.316456,0.506849,0.175,0.397590,0.518072,0.619048,0.270270,0.469880,...,0.014493,-0.166667,0.590361,0.048780,-0.536585,0.404762,0.365854,-0.050,0.324324,0.238095
16130,-0.414634,-0.129412,0.012658,0.150685,-0.475,-0.132530,-0.132530,-0.357143,0.108108,0.084337,...,0.130435,-0.111111,-0.108434,0.121951,-0.121951,-0.238095,-0.073171,-0.150,-0.108108,-0.309524
16131,-0.390244,-0.576471,0.569620,-0.068493,-0.350,-0.614458,-0.421687,-0.285714,0.027027,-0.156627,...,0.275362,0.694444,-0.397590,0.609756,0.365854,-0.428571,-0.341463,0.075,0.135135,0.476190
16132,0.170732,-0.200000,0.240506,0.534247,-0.025,0.325301,-0.132530,-0.071429,0.351351,0.421687,...,0.478261,0.333333,-0.012048,0.634146,0.731707,0.142857,0.000000,-0.100,0.405405,0.666667
16133,0.097561,-0.694118,0.443038,0.150685,-0.600,-0.397590,-0.421687,-0.642857,0.081081,0.108434,...,-0.275362,0.555556,-0.566265,0.585366,0.658537,-0.714286,-0.048780,-0.150,0.216216,0.428571

,"Poor:[np.float64(46.0), np.float64(62.0)]","Interm:[np.float64(63.0), np.float64(66.0)]","Good:[np.float64(67.0), np.float64(71.0)]","Excel:[np.float64(72.0), np.float64(94.0)]"
0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0
...,...,...,...,...
16129,0.0,0.0,0.0,1.0
16130,1.0,0.0,0.0,0.0
16131,0.0,0.0,1.0,0.0
16132,0.0,0.0,0.0,1.0
16133,0.0,0.0,0.0,1.0

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_temp , Y_train, Y_temp = train_test_split(df_clean, df_one_hot, test_size=0.2, random_state=42)
X_test, X_val, Y_test, Y_val = train_test_split(X_temp, Y_temp, test_size=0.5, random_state=42)

In [8]:
input_dim = len(X_train.columns)
output_dim = len(Y_train.columns)
modelo = keras.Sequential([
    keras.Input(shape=(input_dim,)),
    keras.layers.Dense(100,activation=keras.activations.relu),
    keras.layers.Dense(100,activation=keras.activations.relu),
    keras.layers.Dense(100,activation=keras.activations.relu),
    keras.layers.Dense(output_dim, activation=keras.activations.softmax)
])

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773076130.568300   66409 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2141 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [ ]:
modelo.compile(optimizer='adam', loss='categorical_crossentropy')
losses = modelo.fit(X_train,Y_train,(X_val,Y_val),epochs=50, batch_size=512)

Epoch 1/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 8s 102ms/step - loss: 0.2706
Epoch 2/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2606
Epoch 3/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2597
Epoch 4/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2616
Epoch 5/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2546
Epoch 6/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2557
Epoch 7/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2539
Epoch 8/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2544
Epoch 9/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2501
Epoch 10/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2481
Epoch 11/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2497
Epoch 12/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2524
Epoch 13/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2569
Epoch 14/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2476
Epoch 15/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2471
Epoch 16/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2507
Epoch 17/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2455
Epoch 18/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2478
Epoch 19/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2466
Epoch 20/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2427
Epoch 21/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2411
Epoch 22/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2383
Epoch 23/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2409
Epoch 24/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2362
Epoch 25/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2348
Epoch 26/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2431
Epoch 27/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2359
Epoch 28/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2319
Epoch 29/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2332
Epoch 30/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2321
Epoch 31/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2366
Epoch 32/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2337
Epoch 33/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2335
Epoch 34/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2309
Epoch 35/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2331
Epoch 36/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2279
Epoch 37/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2277
Epoch 38/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2286
Epoch 39/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2255
Epoch 40/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2225
Epoch 41/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2229
Epoch 42/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2210
Epoch 43/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2197
Epoch 44/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2174
Epoch 45/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2194
Epoch 46/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2166
Epoch 47/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2233
Epoch 48/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2175
Epoch 49/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2141
Epoch 50/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2142

In [ ]:
plt.plot()

{'loss': [0.27056464552879333,
  0.2605850100517273,
  0.25966259837150574,
  0.26157474517822266,
  0.2546258270740509,
  0.2556505501270294,
  0.2539003789424896,
  0.25438475608825684,
  0.2501067817211151,
  0.2480936199426651,
  0.24967537820339203,
  0.25236210227012634,
  0.25693562626838684,
  0.24764561653137207,
  0.2470724880695343,
  0.25073108077049255,
  0.24554535746574402,
  0.24782617390155792,
  0.2465534508228302,
  0.242677241563797,
  0.24106530845165253,
  0.23826803267002106,
  0.24092243611812592,
  0.236225426197052,
  0.23480767011642456,
  0.24311567842960358,
  0.23585155606269836,
  0.23190857470035553,
  0.23323847353458405,
  0.23213350772857666,
  0.23658892512321472,
  0.23366209864616394,
  0.23353053629398346,
  0.2309471219778061,
  0.23309065401554108,
  0.2278507500886917,
  0.22770629823207855,
  0.2285611778497696,
  0.22549226880073547,
  0.2225492149591446,
  0.22293931245803833,
  0.22100834548473358,
  0.21970893442630768,
  0.217441588640213,
  0.2193862497806549,
  0.2166324406862259,
  0.2232789695262909,
  0.21745191514492035,
  0.21406424045562744,
  0.21415385603904724]}